export interface Consulta {
    empresaId?:string
    clienteId?:string
    _id?:string  
    fecha?:string
        rango_od?:string
        rango_oi?:string
        add_cerca?:string
        lod_esfera?:string
        lod_cilindro?:string
        lod_eje?:string
        lod_prisma?:string
        lod_av?:string
        lod_dip?:string
        cod_esfera?:string
        cod_cilindro?:string
        cod_eje?:string
        cod_prisma?:string
        cod_av?:string
        cod_dip?:string
        loi_esfera?:string
        loi_cilindro?:string
        loi_eje?:string
        loi_prisma?:string
        loi_av?:string
        loi_dip?:string
        coi_esfera?:string
        coi_cilindro?:string
        coi_eje?:string
        coi_prisma?:string
        coi_av?:string
        coi_dip?:string
        codigo_estado?:string
        usu_crea?:string
        fec_crea?:Date
        usu_modi?:string
        fec_modi?:Date
}